[book]
authors = ["houseme"]
language = "en"
multilingual = false
src = "src"
title = "learn-lang"
description = "Progressively master programming languages by dissecting the cores of popular ones like Rust and Go."

[rust]
edition = "2018"

[build]
build-dir = "book"
create-missing = false